name: Push strings to transifex

on:
  push:
    - master


# Allow one concurrent deployment
concurrency:
  group: "tx_push"
  cancel-in-progress: true

jobs:
  update:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          pip install -r REQUIREMENTS.txt

      - name: Generate translation sources
        run: |
            make pretranslate
            ./scripts/create_transifex_resources.sh

      - name: Push translations
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
            tx push -s
